apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: dep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dep
  template:
    metadata:
      labels:
        app: dep
    spec:
      containers:
      - name: dep
        image: nginx:1.14.2
        ports:
        - containerPort: 80
